/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPapersDotxmlRouteImport } from './routes/sitemap-papers[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapCoursesDotxmlRouteImport } from './routes/sitemap-courses[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PapersPaperIdRouteImport } from './routes/papers/$paperId'
import { Route as OrderReferenceRouteImport } from './routes/order/$reference'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses/$courseSlug/index'
import { Route as ApiAdminPapersRouteImport } from './routes/api/admin/papers'
import { Route as CoursesCourseSlugLevelSlugIndexRouteImport } from './routes/courses/$courseSlug/$levelSlug/index'
import { Route as ApiPublicCloudcodePapersRouteImport } from './routes/api/public/cloudcode/papers'
import { Route as ApiPublicCheckoutStatusRouteImport } from './routes/api/public/checkout/status'
import { Route as ApiPublicCheckoutMyOrdersRouteImport } from './routes/api/public/checkout/my-orders'
import { Route as ApiPublicCheckoutInitiateRouteImport } from './routes/api/public/checkout/initiate'
import { Route as ApiPublicCheckoutDownloadUrlRouteImport } from './routes/api/public/checkout/download-url'
import { Route as ApiPublicAdminPricesRouteImport } from './routes/api/public/admin/prices'
import { Route as ApiPublicAdminPapersRouteImport } from './routes/api/public/admin/papers'
import { Route as ApiPublicAdminOrdersRouteImport } from './routes/api/public/admin/orders'
import { Route as ApiPublicPalplussWebhookSecretRouteImport } from './routes/api/public/palpluss/webhook/$secret'
import { Route as ApiPublicDownloadReferencePaperIdRouteImport } from './routes/api/public/download/$reference/$paperId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPapersDotxmlRoute = SitemapPapersDotxmlRouteImport.update({
  id: '/sitemap-papers.xml',
  path: '/sitemap-papers.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCoursesDotxmlRoute = SitemapCoursesDotxmlRouteImport.update({
  id: '/sitemap-courses.xml',
  path: '/sitemap-courses.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/courses/$courseSlug/',
  path: '/courses/$courseSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPapersRoute = ApiAdminPapersRouteImport.update({
  id: '/api/admin/papers',
  path: '/api/admin/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugLevelSlugIndexRoute =
  CoursesCourseSlugLevelSlugIndexRouteImport.update({
    id: '/courses/$courseSlug/$levelSlug/',
    path: '/courses/$courseSlug/$levelSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudcodePapersRoute =
  ApiPublicCloudcodePapersRouteImport.update({
    id: '/api/public/cloudcode/papers',
    path: '/api/public/cloudcode/papers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckoutStatusRoute = ApiPublicCheckoutStatusRouteImport.update({
  id: '/api/public/checkout/status',
  path: '/api/public/checkout/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutMyOrdersRoute =
  ApiPublicCheckoutMyOrdersRouteImport.update({
    id: '/api/public/checkout/my-orders',
    path: '/api/public/checkout/my-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckoutInitiateRoute =
  ApiPublicCheckoutInitiateRouteImport.update({
    id: '/api/public/checkout/initiate',
    path: '/api/public/checkout/initiate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckoutDownloadUrlRoute =
  ApiPublicCheckoutDownloadUrlRouteImport.update({
    id: '/api/public/checkout/download-url',
    path: '/api/public/checkout/download-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminPricesRoute = ApiPublicAdminPricesRouteImport.update({
  id: '/api/public/admin/prices',
  path: '/api/public/admin/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminPapersRoute = ApiPublicAdminPapersRouteImport.update({
  id: '/api/public/admin/papers',
  path: '/api/public/admin/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminOrdersRoute = ApiPublicAdminOrdersRouteImport.update({
  id: '/api/public/admin/orders',
  path: '/api/public/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPalplussWebhookSecretRoute =
  ApiPublicPalplussWebhookSecretRouteImport.update({
    id: '/api/public/palpluss/webhook/$secret',
    path: '/api/public/palpluss/webhook/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDownloadReferencePaperIdRoute =
  ApiPublicDownloadReferencePaperIdRouteImport.update({
    id: '/api/public/download/$reference/$paperId',
    path: '/api/public/download/$reference/$paperId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-courses.xml': typeof SitemapCoursesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-papers.xml': typeof SitemapPapersDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/admin/papers': typeof ApiAdminPapersRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/admin/papers': typeof ApiPublicAdminPapersRoute
  '/api/public/admin/prices': typeof ApiPublicAdminPricesRoute
  '/api/public/checkout/download-url': typeof ApiPublicCheckoutDownloadUrlRoute
  '/api/public/checkout/initiate': typeof ApiPublicCheckoutInitiateRoute
  '/api/public/checkout/my-orders': typeof ApiPublicCheckoutMyOrdersRoute
  '/api/public/checkout/status': typeof ApiPublicCheckoutStatusRoute
  '/api/public/cloudcode/papers': typeof ApiPublicCloudcodePapersRoute
  '/courses/$courseSlug/$levelSlug/': typeof CoursesCourseSlugLevelSlugIndexRoute
  '/api/public/download/$reference/$paperId': typeof ApiPublicDownloadReferencePaperIdRoute
  '/api/public/palpluss/webhook/$secret': typeof ApiPublicPalplussWebhookSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-courses.xml': typeof SitemapCoursesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-papers.xml': typeof SitemapPapersDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/api/admin/papers': typeof ApiAdminPapersRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/admin/papers': typeof ApiPublicAdminPapersRoute
  '/api/public/admin/prices': typeof ApiPublicAdminPricesRoute
  '/api/public/checkout/download-url': typeof ApiPublicCheckoutDownloadUrlRoute
  '/api/public/checkout/initiate': typeof ApiPublicCheckoutInitiateRoute
  '/api/public/checkout/my-orders': typeof ApiPublicCheckoutMyOrdersRoute
  '/api/public/checkout/status': typeof ApiPublicCheckoutStatusRoute
  '/api/public/cloudcode/papers': typeof ApiPublicCloudcodePapersRoute
  '/courses/$courseSlug/$levelSlug': typeof CoursesCourseSlugLevelSlugIndexRoute
  '/api/public/download/$reference/$paperId': typeof ApiPublicDownloadReferencePaperIdRoute
  '/api/public/palpluss/webhook/$secret': typeof ApiPublicPalplussWebhookSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-courses.xml': typeof SitemapCoursesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-papers.xml': typeof SitemapPapersDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/admin/papers': typeof ApiAdminPapersRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/admin/papers': typeof ApiPublicAdminPapersRoute
  '/api/public/admin/prices': typeof ApiPublicAdminPricesRoute
  '/api/public/checkout/download-url': typeof ApiPublicCheckoutDownloadUrlRoute
  '/api/public/checkout/initiate': typeof ApiPublicCheckoutInitiateRoute
  '/api/public/checkout/my-orders': typeof ApiPublicCheckoutMyOrdersRoute
  '/api/public/checkout/status': typeof ApiPublicCheckoutStatusRoute
  '/api/public/cloudcode/papers': typeof ApiPublicCloudcodePapersRoute
  '/courses/$courseSlug/$levelSlug/': typeof CoursesCourseSlugLevelSlugIndexRoute
  '/api/public/download/$reference/$paperId': typeof ApiPublicDownloadReferencePaperIdRoute
  '/api/public/palpluss/webhook/$secret': typeof ApiPublicPalplussWebhookSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap-blog.xml'
    | '/sitemap-courses.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-papers.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/order/$reference'
    | '/papers/$paperId'
    | '/blog/'
    | '/courses/'
    | '/api/admin/papers'
    | '/courses/$courseSlug/'
    | '/api/public/admin/orders'
    | '/api/public/admin/papers'
    | '/api/public/admin/prices'
    | '/api/public/checkout/download-url'
    | '/api/public/checkout/initiate'
    | '/api/public/checkout/my-orders'
    | '/api/public/checkout/status'
    | '/api/public/cloudcode/papers'
    | '/courses/$courseSlug/$levelSlug/'
    | '/api/public/download/$reference/$paperId'
    | '/api/public/palpluss/webhook/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap-blog.xml'
    | '/sitemap-courses.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-papers.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/order/$reference'
    | '/papers/$paperId'
    | '/blog'
    | '/courses'
    | '/api/admin/papers'
    | '/courses/$courseSlug'
    | '/api/public/admin/orders'
    | '/api/public/admin/papers'
    | '/api/public/admin/prices'
    | '/api/public/checkout/download-url'
    | '/api/public/checkout/initiate'
    | '/api/public/checkout/my-orders'
    | '/api/public/checkout/status'
    | '/api/public/cloudcode/papers'
    | '/courses/$courseSlug/$levelSlug'
    | '/api/public/download/$reference/$paperId'
    | '/api/public/palpluss/webhook/$secret'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/sitemap-blog.xml'
    | '/sitemap-courses.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-papers.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/order/$reference'
    | '/papers/$paperId'
    | '/blog/'
    | '/courses/'
    | '/api/admin/papers'
    | '/courses/$courseSlug/'
    | '/api/public/admin/orders'
    | '/api/public/admin/papers'
    | '/api/public/admin/prices'
    | '/api/public/checkout/download-url'
    | '/api/public/checkout/initiate'
    | '/api/public/checkout/my-orders'
    | '/api/public/checkout/status'
    | '/api/public/cloudcode/papers'
    | '/courses/$courseSlug/$levelSlug/'
    | '/api/public/download/$reference/$paperId'
    | '/api/public/palpluss/webhook/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapCoursesDotxmlRoute: typeof SitemapCoursesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapPapersDotxmlRoute: typeof SitemapPapersDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAdminPapersRoute: typeof ApiAdminPapersRoute
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  ApiPublicAdminOrdersRoute: typeof ApiPublicAdminOrdersRoute
  ApiPublicAdminPapersRoute: typeof ApiPublicAdminPapersRoute
  ApiPublicAdminPricesRoute: typeof ApiPublicAdminPricesRoute
  ApiPublicCheckoutDownloadUrlRoute: typeof ApiPublicCheckoutDownloadUrlRoute
  ApiPublicCheckoutInitiateRoute: typeof ApiPublicCheckoutInitiateRoute
  ApiPublicCheckoutMyOrdersRoute: typeof ApiPublicCheckoutMyOrdersRoute
  ApiPublicCheckoutStatusRoute: typeof ApiPublicCheckoutStatusRoute
  ApiPublicCloudcodePapersRoute: typeof ApiPublicCloudcodePapersRoute
  CoursesCourseSlugLevelSlugIndexRoute: typeof CoursesCourseSlugLevelSlugIndexRoute
  ApiPublicDownloadReferencePaperIdRoute: typeof ApiPublicDownloadReferencePaperIdRoute
  ApiPublicPalplussWebhookSecretRoute: typeof ApiPublicPalplussWebhookSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-papers.xml': {
      id: '/sitemap-papers.xml'
      path: '/sitemap-papers.xml'
      fullPath: '/sitemap-papers.xml'
      preLoaderRoute: typeof SitemapPapersDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-courses.xml': {
      id: '/sitemap-courses.xml'
      path: '/sitemap-courses.xml'
      fullPath: '/sitemap-courses.xml'
      preLoaderRoute: typeof SitemapCoursesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/papers': {
      id: '/api/admin/papers'
      path: '/api/admin/papers'
      fullPath: '/api/admin/papers'
      preLoaderRoute: typeof ApiAdminPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/$levelSlug/': {
      id: '/courses/$courseSlug/$levelSlug/'
      path: '/courses/$courseSlug/$levelSlug'
      fullPath: '/courses/$courseSlug/$levelSlug/'
      preLoaderRoute: typeof CoursesCourseSlugLevelSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudcode/papers': {
      id: '/api/public/cloudcode/papers'
      path: '/api/public/cloudcode/papers'
      fullPath: '/api/public/cloudcode/papers'
      preLoaderRoute: typeof ApiPublicCloudcodePapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/status': {
      id: '/api/public/checkout/status'
      path: '/api/public/checkout/status'
      fullPath: '/api/public/checkout/status'
      preLoaderRoute: typeof ApiPublicCheckoutStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/my-orders': {
      id: '/api/public/checkout/my-orders'
      path: '/api/public/checkout/my-orders'
      fullPath: '/api/public/checkout/my-orders'
      preLoaderRoute: typeof ApiPublicCheckoutMyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/initiate': {
      id: '/api/public/checkout/initiate'
      path: '/api/public/checkout/initiate'
      fullPath: '/api/public/checkout/initiate'
      preLoaderRoute: typeof ApiPublicCheckoutInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/download-url': {
      id: '/api/public/checkout/download-url'
      path: '/api/public/checkout/download-url'
      fullPath: '/api/public/checkout/download-url'
      preLoaderRoute: typeof ApiPublicCheckoutDownloadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/prices': {
      id: '/api/public/admin/prices'
      path: '/api/public/admin/prices'
      fullPath: '/api/public/admin/prices'
      preLoaderRoute: typeof ApiPublicAdminPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/papers': {
      id: '/api/public/admin/papers'
      path: '/api/public/admin/papers'
      fullPath: '/api/public/admin/papers'
      preLoaderRoute: typeof ApiPublicAdminPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/orders': {
      id: '/api/public/admin/orders'
      path: '/api/public/admin/orders'
      fullPath: '/api/public/admin/orders'
      preLoaderRoute: typeof ApiPublicAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/palpluss/webhook/$secret': {
      id: '/api/public/palpluss/webhook/$secret'
      path: '/api/public/palpluss/webhook/$secret'
      fullPath: '/api/public/palpluss/webhook/$secret'
      preLoaderRoute: typeof ApiPublicPalplussWebhookSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$reference/$paperId': {
      id: '/api/public/download/$reference/$paperId'
      path: '/api/public/download/$reference/$paperId'
      fullPath: '/api/public/download/$reference/$paperId'
      preLoaderRoute: typeof ApiPublicDownloadReferencePaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapCoursesDotxmlRoute: SitemapCoursesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapPapersDotxmlRoute: SitemapPapersDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAdminPapersRoute: ApiAdminPapersRoute,
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  ApiPublicAdminOrdersRoute: ApiPublicAdminOrdersRoute,
  ApiPublicAdminPapersRoute: ApiPublicAdminPapersRoute,
  ApiPublicAdminPricesRoute: ApiPublicAdminPricesRoute,
  ApiPublicCheckoutDownloadUrlRoute: ApiPublicCheckoutDownloadUrlRoute,
  ApiPublicCheckoutInitiateRoute: ApiPublicCheckoutInitiateRoute,
  ApiPublicCheckoutMyOrdersRoute: ApiPublicCheckoutMyOrdersRoute,
  ApiPublicCheckoutStatusRoute: ApiPublicCheckoutStatusRoute,
  ApiPublicCloudcodePapersRoute: ApiPublicCloudcodePapersRoute,
  CoursesCourseSlugLevelSlugIndexRoute: CoursesCourseSlugLevelSlugIndexRoute,
  ApiPublicDownloadReferencePaperIdRoute:
    ApiPublicDownloadReferencePaperIdRoute,
  ApiPublicPalplussWebhookSecretRoute: ApiPublicPalplussWebhookSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
